### ISSUE TITLE
DOWNLOAD_DIRECTORY & DOWNLOAD_QUEUE_FOLDER?  Not documented

### ISSUE THREAD

**Issue by jeff47** [ligh7s/smoked-salmon#42]
Two options appear in the example config.py that I can't find in the documentation:
DOWNLOAD_DIRECTORY =
DOWNLOAD_QUEUE_FOLDER = '/path/to/folder/for/the/queue'

What are they supposed to do?  They don't seem to do anything that I can see...

**Comment by jeff47** [comment]
DOH, never mind.  I see it in the code, just seem to check for overall filename length.

**Comment by AN1MATEK** [comment]
I am in the same situation as you were. Would you care to explain what they do?
